### ISSUE TITLE
Create new products trough images

### ISSUE THREAD

**Issue by matteoraggi** [Naahuel/WooCommerce-Batch-Image-Import#2]
I suggest to add the feature to add new products trough the images, any tricks or idea to do it?

**Comment by Naahuel** [comment]
Hey @matteoraggi, sorry for the long delay! I haven't used this plugin in years!

About your request, I have no plans on continuing development of this plugin. Creating new products if they don't exist when importing the images should be easy since products are just posts with custom a post type (there's more things you need to do because WC adds A LOT of meta fields and keeps some information in different tables so you need to use the WC API or set those meta fields manually).
